### ISSUE TITLE
Create a better README.md

### ISSUE THREAD

**Issue by jasonappah** [hack-as-a-service/frontend#144]
Right now we're still using the stock `create-next-app` readme, and we should probably update that to have info about HaaS in general, setting up a basic dev environment, etc.

**Comment by J-cordz** [comment]
Hi! I had this issue assigned, but at that moment I couldn't work on it and today I did an improved version that adds some new features and solves some errors. 
**You can see it at:** https://github.com/hack-as-a-service/frontend/pull/194
