### ISSUE TITLE
Deploy Logs Page Not Working on Safari

### ISSUE THREAD

**Issue by LinusS1** [hack-as-a-service/frontend#156]
![C1E64D2E-EC4B-4489-9678-EF51DC699FD3](https://user-images.githubusercontent.com/19542092/149011664-fb148d2c-d38c-4786-8e9d-33b14e310547.png)
When I try to see the logs in safari after I try to deploy an app it errors with this page. In Firefox it does not error.

**Comment by cjdenio** [comment]
`Array.at()` is experimental (and doesn't work in Safari): https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

**Comment by anirudhb** [comment]
Fixed by the aforementioned commit. Thanks for reporting!
