### ISSUE TITLE
Fix lint errors

### ISSUE THREAD

**Issue by anirudhb** [hack-as-a-service/frontend#37]
Either fix the errors or disable that lint. cc @jasonappah assigning you to this

**Comment by jasonappah** [comment]
Which issues need to be fixed? The lint workflow seems to be fine and I'm not encountering any errors with it locally

**Comment by jasonappah** [comment]
NVM just saw f6317ca - I'll just disable that rule ig

**Comment by anirudhb** [comment]
They are warnings, which you can see when you run `yarn lint` -- I don't think any rules should be disabled, rather we should fix our code.
