### ISSUE TITLE
Build user settings page

### ISSUE THREAD

**Issue by jasonappah** [hack-as-a-service/frontend#8]

**Comment by cjdenio** [comment]
Possibly unnecessary because auth is handled by Slack

**Comment by jasonappah** [comment]
I think the only thing that we needed here was to delete users from HaaS and allow users to export their data as well (iirc this was for GDPR compliance?)

**Comment by anirudhb** [comment]
This seems stale-- we have a basic user settings page now with "delete" and "export" (although they don't work yet.)
